[theme]
primaryColor = "#4c78a8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false
